### ISSUE TITLE
mybinder notebooks is stoped working

### ISSUE THREAD

**Issue by unimado1** [a2nk/notebooks#1]
Hi! Recently mybinder notebooks just stoped working :( ![IMG_20220429_230353.jpg](https://user-images.githubusercontent.com/104565294/166009848-07936479-a89b-400a-849d-c84f7936a310.jpg) Maybe you can do anything to fix that! Good luck with that!

**Comment by a2nk** [comment]
Hi,
Mybinder is working now!
